version: '3.4'

services:

  # 1
  postgres:
    image: postgres:latest
    container_name: "peerid.postgres"
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data
    restart: always
    ports:
      - 5432:5432


  # 2
  backend.api:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["npm", "run", "start"]
    env_file:
      - .env
    container_name: "peerid.backend.api"
    ports:
      - 3000:3000
    restart: always
    depends_on:
      - postgres

volumes:
  postgres:

